import ConjointSD

-- Scratchpad to inspect SD-consistency assumptions.

#print ConjointSD.ScoreAssumptions.int_g0
#print ConjointSD.SplitEvalAssumptions
#print ConjointSD.FunctionalContinuityAssumptions
#print ConjointSD.attrMean_tendsto_of_theta_tendsto
#print ConjointSD.attrM2_tendsto_of_theta_tendsto
#print ConjointSD.attrSD_tendsto_of_mean_m2_tendsto
#print ConjointSD.functionalContinuity_gLin_of_bounded
#print ConjointSD.functionalContinuity_gTotalΘ_of_bounded
#print ConjointSD.functionalContinuity_gBlockTerm_of_bounded
#print ConjointSD.paper_ols_gramInv_tendsto_of_design_ae
#print ConjointSD.paper_ols_theta0_eq_of_normal_eq
#print ConjointSD.paper_ols_normal_eq_of_wellSpecified
#print ConjointSD.ConjointIdRandomized
#print ConjointSD.ConjointRandomizationStream
#print ConjointSD.DesignAttrIID.of_randomization_stream
-- Core SD and decomposition.
#print ConjointSD.sd_component_consistent
#print ConjointSD.sd_component_consistent_of_design
#print ConjointSD.meanHatZ_tendsto_ae_of_score
#print ConjointSD.sdHatZ_tendsto_ae_of_score
#print ConjointSD.sdHatZW_tendsto_ae_of_score

-- Sample splitting (evaluation stage).
#print ConjointSD.sdHat_fixed_m_tendsto_ae_attrSD

-- Sequential consistency (train then eval).
#print ConjointSD.totalErr_tendsto_trainErr_fixed_m
#print ConjointSD.trainErr_tendsto_zero
#print ConjointSD.sequential_consistency_ae

-- Decomposition sequential consistency.
#print ConjointSD.sequential_consistency_blocks_ae
#print ConjointSD.sequential_consistency_total_ae
#print ConjointSD.sequential_consistency_blocks_ae_of_bounded
#print ConjointSD.sequential_consistency_total_ae_of_bounded

-- Identification.
#print ConjointSD.condMean_eq_potMean_of_rand
#print ConjointSD.ae_restrict_consistency
#print ConjointSD.identified_potMean_from_condMean
#print ConjointSD.identified_amce_from_condMeans
#print ConjointSD.gExp_eq_gPot

-- Target equivalence and approximation bounds.
#print ConjointSD.attrMean_congr_ae
#print ConjointSD.attrM2_congr_ae
#print ConjointSD.attrVar_congr_ae
#print ConjointSD.attrSD_congr_ae
#print ConjointSD.approxInvarianceAE_triangle
#print ConjointSD.attrMean_diff_le_of_L2Approx
#print ConjointSD.attrSD_diff_le_of_L2Approx
#print ConjointSD.attrMean_abs_le_of_bounded_ae
#print ConjointSD.attrMean_diff_le_of_approx_ae
#print ConjointSD.attrM2_diff_le_of_approx_ae
#print ConjointSD.attrVar_diff_le_of_approx_ae
#print ConjointSD.attrSD_diff_le_of_approx_ae
#print ConjointSD.attrSD_eq_of_moments

-- Model bridge.
#print ConjointSD.gLin_eq_gTotal_blocks
#print ConjointSD.gStar_eq_sum_blocks_of_WellSpecified
#print ConjointSD.gStar_approx_sum_blocks_of_ApproxWellSpecified
#print ConjointSD.gStar_approx_sum_blocks_of_ApproxWellSpecifiedAE
#print ConjointSD.wellSpecified_of_noInteractions_of_fullMainEffects
#print ConjointSD.approxWellSpecified_of_approxNoInteractions_of_fullMainEffects

-- Paper core estimands.
#print ConjointSD.paperBlockSDs_apply
#print ConjointSD.paperTotalSD_def
#print ConjointSD.paper_total_sd_estimator_consistency_ae_of_gBTerm
#print ConjointSD.gTotalΘ_eq_gTotal_gBTerm
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_ae_of_gBTerm

-- Paper-facing wrappers.
#print ConjointSD.paper_identifies_potMean_from_condMean
#print ConjointSD.paper_identifies_amce_from_condMeans
#print ConjointSD.paper_identifies_potMean_from_condMean_status
#print ConjointSD.paper_identifies_amce_from_condMeans_status
#print ConjointSD.paper_gStar_eq_sum_blocks_of_WellSpecified
#print ConjointSD.paper_sd_blocks_sequential_consistency_ae
#print ConjointSD.paper_sd_blocks_sequential_consistency_ae_of_bounded
#print ConjointSD.paper_sd_total_sequential_consistency_ae
#print ConjointSD.paper_sd_total_sequential_consistency_ae_of_bounded
#print ConjointSD.paper_sd_blocks_and_total_sequential_consistency_ae
#print ConjointSD.paper_sd_blocks_and_total_sequential_consistency_ae_of_bounded
#print ConjointSD.paper_sd_blocks_sequential_consistency_to_true_target_ae
#print ConjointSD.paper_sd_blocks_sequential_consistency_to_approx_target_ae
#print ConjointSD.paper_sd_total_sequential_consistency_to_approx_target_ae
#print ConjointSD.paper_sd_total_sequential_consistency_to_true_target_ae
#print ConjointSD.paper_sd_total_sequential_consistency_to_gPot_ae_of_identification
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_approx_ae_of_ApproxWellSpecifiedAE
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_approx_ae_of_ApproxOracleAE
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_ae_of_WellSpecified
#print ConjointSD.paper_sd_blocks_and_total_sequential_consistency_ae_of_paper_ols_moments
#print ConjointSD.paper_sd_total_sequential_consistency_ae_of_hGTotal
#print ConjointSD.paper_sd_total_sequential_consistency_ae_of_paper_ols_gStar_total
#print ConjointSD.paper_sd_total_sequential_consistency_ae_of_paper_ols_design_total_ae
#print ConjointSD.paper_ols_attr_moments_of_design_ae
#print ConjointSD.paper_sd_total_sequential_consistency_to_true_target_ae_of_hGTotal
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_ae_of_WellSpecified_of_hGTotal
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_ae_of_NoInteractions
