import ConjointSD

-- Scratchpad to inspect SD-consistency assumptions.

#print ConjointSD.ScoreAssumptions.int_g0
#print ConjointSD.SplitEvalAssumptions
#print ConjointSD.FunctionalContinuityAssumptions
#print ConjointSD.attrMean_tendsto_of_theta_tendsto
#print ConjointSD.attrM2_tendsto_of_theta_tendsto
#print ConjointSD.attrSD_tendsto_of_mean_m2_tendsto
#print ConjointSD.olsThetaHat_tendsto_of_moment_assumptions
#print ConjointSD.olsThetaHat_tendsto_of_moment_assumptions_id
#print ConjointSD.olsThetaHat_tendsto_of_attr_moments
#print ConjointSD.functionalContinuity_gLin_of_bounded
#print ConjointSD.functionalContinuity_gTotalΘ_of_bounded
#print ConjointSD.functionalContinuity_gBlockTerm_of_bounded
#print ConjointSD.paper_ols_gramInv_tendsto_of_design_ae
#print ConjointSD.paper_ols_fullRank_of_orthogonal
#print ConjointSD.paper_ols_fullRank_of_posDef
#print ConjointSD.paper_ols_theta0_eq_of_normal_eq
#print ConjointSD.paper_ols_normal_eq_of_wellSpecified
#print ConjointSD.theta_tendsto_of_paper_ols_moments
#print ConjointSD.theta_tendsto_of_paper_ols_design_ae
#print ConjointSD.ConjointIdRandomized
#print ConjointSD.ConjointRandomizationStream
#print ConjointSD.DesignAttrIID.of_randomization_stream
-- Core SD and decomposition.
#print ConjointSD.sd_component_consistent
#print ConjointSD.meanHatZ_tendsto_ae_of_score
#print ConjointSD.sdHatZ_tendsto_ae_of_score
#print ConjointSD.sdHatZW_tendsto_ae_of_score

-- Sample splitting (evaluation stage).
#print ConjointSD.sdHat_fixed_m_tendsto_ae_attrSD

-- Sequential consistency (train then eval).
#print ConjointSD.totalErr_tendsto_trainErr_fixed_m
#print ConjointSD.trainErr_tendsto_zero
#print ConjointSD.sequential_consistency_ae

-- Decomposition sequential consistency.
#print ConjointSD.sequential_consistency_blocks_ae
#print ConjointSD.sequential_consistency_total_ae
#print ConjointSD.sequential_consistency_blocks_ae_of_bounded
#print ConjointSD.sequential_consistency_total_ae_of_bounded

-- Identification.
#print ConjointSD.condMean_eq_potMean_of_rand
#print ConjointSD.ae_restrict_consistency
#print ConjointSD.identified_potMean_from_condMean
#print ConjointSD.identified_amce_from_condMeans
#print ConjointSD.gExp_eq_gPot

-- Target equivalence and approximation bounds.
#print ConjointSD.attrMean_congr_ae
#print ConjointSD.attrM2_congr_ae
#print ConjointSD.attrVar_congr_ae
#print ConjointSD.attrSD_congr_ae
#print ConjointSD.approxInvarianceAE_triangle
#print ConjointSD.attrMean_diff_le_of_L2Approx
#print ConjointSD.attrSD_diff_le_of_L2Approx
#print ConjointSD.attrMean_abs_le_of_bounded_ae
#print ConjointSD.attrMean_diff_le_of_approx_ae
#print ConjointSD.attrM2_diff_le_of_approx_ae
#print ConjointSD.attrVar_diff_le_of_approx_ae
#print ConjointSD.attrSD_diff_le_of_approx_ae

-- Model bridge.
#print ConjointSD.gLin_eq_gTotal_blocks
#print ConjointSD.gStar_eq_sum_blocks_of_WellSpecified
#print ConjointSD.gStar_approx_sum_blocks_of_ApproxWellSpecified
#print ConjointSD.gStar_approx_sum_blocks_of_ApproxWellSpecifiedAE
#print ConjointSD.approxWellSpecified_of_approxNoInteractions_of_fullMainEffects

-- Paper core estimands.
#print ConjointSD.paperBlockSDs_apply
#print ConjointSD.paperTotalSD_def
#print ConjointSD.paper_total_sd_estimator_consistency_ae_of_gBTerm
#print ConjointSD.gTotalΘ_eq_gTotal_gBTerm
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_ae_of_gBTerm

-- Paper-facing wrappers.
#print ConjointSD.paper_identifies_potMean_from_condMean
#print ConjointSD.paper_identifies_amce_from_condMeans
#print ConjointSD.paper_identifies_potMean_from_condMean_status
#print ConjointSD.paper_identifies_amce_from_condMeans_status
#print ConjointSD.paper_gStar_eq_sum_blocks_of_WellSpecified
#print ConjointSD.paper_sd_blocks_sequential_consistency_ae
#print ConjointSD.paper_sd_blocks_sequential_consistency_ae_of_bounded
#print ConjointSD.paper_sd_total_sequential_consistency_ae
#print ConjointSD.paper_sd_total_sequential_consistency_ae_of_bounded
#print ConjointSD.paper_sd_blocks_and_total_sequential_consistency_ae
#print ConjointSD.paper_sd_blocks_and_total_sequential_consistency_ae_of_bounded
#print ConjointSD.paper_sd_blocks_sequential_consistency_to_true_target_ae
#print ConjointSD.paper_sd_blocks_sequential_consistency_to_approx_target_ae
#print ConjointSD.paper_sd_total_sequential_consistency_to_approx_target_ae
#print ConjointSD.paper_sd_total_sequential_consistency_to_true_target_ae
#print ConjointSD.paper_sd_total_sequential_consistency_to_gPot_ae_of_identification
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_approx_ae_of_ApproxWellSpecifiedAE
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_approx_ae_of_ApproxOracleAE
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_ae_of_WellSpecified
#print ConjointSD.paper_sd_blocks_and_total_sequential_consistency_ae_of_paper_ols_design_ae
#print ConjointSD.paper_sd_total_sequential_consistency_ae_of_hGTotal
#print ConjointSD.paper_sd_total_sequential_consistency_ae_of_paper_ols_gStar_total
#print ConjointSD.paper_sd_total_sequential_consistency_ae_of_paper_ols_design_total_ae
#print ConjointSD.paper_ols_attr_moments_of_design_ae
#print ConjointSD.paper_sd_total_sequential_consistency_to_true_target_ae_of_hGTotal
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_ae_of_WellSpecified_of_hGTotal
#print ConjointSD.paper_sd_total_sequential_consistency_to_gStar_ae_of_NoInteractions



-- Auto-generated DAG coverage: all ConjointSD theorems.
#print ConjointSD.attrM2_tendsto_of_OLSConsistency
#print ConjointSD.attrM2_tendsto_of_m2_tendsto
#print ConjointSD.attrM2_tendsto_of_paper_ols_design_ae
#print ConjointSD.attrM2_tendsto_of_paper_ols_gStar
#print ConjointSD.attrM2_tendsto_of_paper_ols_gStar_total
#print ConjointSD.attrM2_tendsto_of_paper_ols_moments_ae
#print ConjointSD.attrM2_tendsto_of_paper_ols_moments_total_ae
#print ConjointSD.attrMean_tendsto_of_OLSConsistency
#print ConjointSD.attrMean_tendsto_of_mean_tendsto
#print ConjointSD.attrMean_tendsto_of_paper_ols_design_ae
#print ConjointSD.attrMean_tendsto_of_paper_ols_gStar
#print ConjointSD.attrMean_tendsto_of_paper_ols_gStar_total
#print ConjointSD.attrMean_tendsto_of_paper_ols_moments_ae
#print ConjointSD.attrMean_tendsto_of_paper_ols_moments_total_ae
#print ConjointSD.attrVar_tendsto_of_mean_m2_tendsto
#print ConjointSD.blockIntegrable_of_bounded
#print ConjointSD.block_attrM2_tendsto_of_theta_tendsto
#print ConjointSD.block_attrMean_tendsto_of_theta_tendsto
#print ConjointSD.derive_m2_tendsto
#print ConjointSD.derive_m2_tendsto_blocks
#print ConjointSD.derive_mean_tendsto
#print ConjointSD.derive_mean_tendsto_blocks
#print ConjointSD.designM2Z_Zcomp_eq_attrM2
#print ConjointSD.designMeanZ_Zcomp_eq_attrMean
#print ConjointSD.designSDZ_Zcomp_eq_attrSD
#print ConjointSD.designVarZ_Zcomp_eq_attrVar
#print ConjointSD.functionalContinuity_gPaper_of_bounded
#print ConjointSD.functionalContinuity_gTotal
#print ConjointSD.gBTerm_blockSpec
#print ConjointSD.gLin_eq_additive
#print ConjointSD.gPaper_eq_gTotal
#print ConjointSD.gStar_eq_sum_trueBlocks_of_WellSpecified
#print ConjointSD.gTotal
#print ConjointSD.int1
#print ConjointSD.int_g0
#print ConjointSD.paper_blocks_converge_to_trueBlockSDs_ae
#print ConjointSD.paper_blocks_converge_to_trueBlockSDs_ae_of_gBTerm
#print ConjointSD.paper_ols_attr_moments_of_lln_fullrank_ae
#print ConjointSD.paper_ols_lln_of_design_ae
#print ConjointSD.paper_ols_lln_of_score_assumptions_ae
#print ConjointSD.paper_sd_blocks_and_total_sequential_consistency_ae_of_paper_ols_design_ae_of_NoInteractions
#print ConjointSD.sd_block_consistent
#print ConjointSD.sd_component_consistent_of_bounded
#print ConjointSD.status_event_pos
#print ConjointSD.status_id_randomized
#print ConjointSD.theta_tendsto_of_paper_ols_moments_ae
#print ConjointSD.varProxy_sum_eq_sum_covRaw
#print ConjointSD.wellSpecified_of_noInteractions
#print ConjointSD.wellSpecified_of_noInteractions_of_fullMainEffects
